version: '3.8'

services:
  calc-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - PORT=8080
    volumes:
      - .env:/app/.env
    restart: unless-stopped
