version: '3.8'

services:
  calc-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - PORT=8080
    volumes:
      - .env:/app/.env
    restart: unless-stopped

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      - SWAGGER_JSON=/swagger.yaml
      - BASE_URL=/
      - SWAGGER_UI_CORS=true
    volumes:
      - ./swagger.yaml:/swagger.yaml
    depends_on:
      - calc-api
