services:

  orchestrator:
    build:
      context: .
      dockerfile: docker/orchestrator/Dockerfile
    ports:
      - '8080:8080'

  agent:
    build:
      context: .
      dockerfile: docker/agent/Dockerfile
    environment:
      - COMPUTING_POWER=25
      - URL=http://orchestrator:8080
    depends_on:
      - orchestrator