openapi: 3.0.0
info:
  title: Calculator API
  description: API для выполнения математических вычислений
  version: 1.0.0
  contact:
    name: sabure-dev
    url: https://github.com/sabure-dev

servers:
  - url: http://localhost:8080
    description: Локальный сервер разработки

paths:
  /api/v1/calculate:
    post:
      tags:
        - Calculation
      summary: Вычисление математического выражения
      description: Принимает строку с математическим выражением и возвращает результат вычисления
      operationId: calculateExpression
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalculationRequest'
      responses:
        '200':
          description: Успешное вычисление
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalculationResponse'
        '405':
          description: Метод не разрешен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Ошибка в запросе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    options:
      tags:
        - Calculation
      summary: CORS support
      description: Enable CORS by returning correct headers
      responses:
        '200':
          description: Успешный preflight запрос
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string

components:
  schemas:
    CalculationRequest:
      type: object
      required:
        - expression
      properties:
        expression:
          type: string
          description: Математическое выражение для вычисления
          example: "(2+2)*2"
    
    CalculationResponse:
      type: object
      properties:
        result:
          type: number
          format: float
          description: Результат вычисления
          example: 8.0
    
    ErrorResponse:
      type: object
      properties:
        result:
          type: number
          format: float
          description: Результат вычисления (0, если ошибка)
          example: 0
        error:
          type: string
          description: Описание ошибки
          example: "Internal server error"

tags:
  - name: Calculation
    description: Операции калькулятора